# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings

title: IHMC Robotics

email: amoucheboeuf@ihmc.us

description: > # this means to ignore newlines until "baseurl:"
  "IHMC researchers have been advancing the state of the art in robotics and exoskeletons since 2002.
  Their work has been bringing attention to the innovative research being done in this quiet beach community of Pensacola
  through successes like our 2nd place finish in the international robotics competition called the DARPA Robotics Challenge.
  The group is led by IHMC’s scientists Jerry Pratt (bipedal walking), Peter Neuhaus (exoskeletons) and Matthew Johnson (human-robot system design)
  who together work on developing advanced humanoid robot capabilities."

baseurl: ""

url: "http://robots.ihmc.us/" # the base hostname & protocol for your site

twitter_username: ihmcrobotics

github_username:  ihmcrobotics

show_drafts: FALSE

# Build settings
markdown: kramdown

